Repository robbinjanssen/home-assistant-omnik-inverter, pull requests merged in 2021-09, with the labels that each got.

#48 Revert "Revert "🔨 Improve the repo workflow""
  .github/dependabot.yml
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/codeql.yaml
  .github/workflows/draft-release.yaml
  .github/workflows/labels.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#49 Improve the config flow
  custom_components/omnik_inverter/__init__.py
  custom_components/omnik_inverter/config_flow.py
  custom_components/omnik_inverter/const.py
  custom_components/omnik_inverter/strings.json
  custom_components/omnik_inverter/translations/en.json
  custom_components/omnik_inverter/translations/nl.json
Labels: enhancement, new-feature

#50 ⬆️ Bump the python package version to 0.5.0
  custom_components/omnik_inverter/manifest.json
Labels: dependencies

#53 Add support for HTML sources
  README.md
  custom_components/omnik_inverter/__init__.py
  custom_components/omnik_inverter/config_flow.py
  custom_components/omnik_inverter/const.py
  custom_components/omnik_inverter/strings.json
  custom_components/omnik_inverter/translations/en.json
  custom_components/omnik_inverter/translations/nl.json
Labels: documentation, new-feature

#52 Bump the python package version
  custom_components/omnik_inverter/manifest.json
Labels: dependencies

#55 Update documentation for HTML support
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#57 Warn the user when trying to migrate config_flow from previous beta
  custom_components/omnik_inverter/__init__.py
  custom_components/omnik_inverter/config_flow.py
  custom_components/omnik_inverter/const.py
Labels: enhancement, minor

#58 Update README and info (HACS)
  README.md
  images/config_flow.gif
  info.md
Labels: documentation
