Repository robbinjanssen/home-assistant-omnik-inverter, pull requests merged in 2022-02, with the labels that each got.

#91 🎆Updates maintenance/license year to 2022
  LICENSE
  README.md
Labels: maintenance

#92 Add issue template to repository
  .github/ISSUE_TEMPLATE.md
Labels: maintenance

#90 Add diagnostics to integration
  custom_components/omnik_inverter/diagnostics.py
Labels: new-feature

#95 Add Hosola 1500TL to supported models
  README.md
Labels: documentation

#82 Ginlong Solis wifistick
  README.md
  custom_components/omnik_inverter/__init__.py
  custom_components/omnik_inverter/config_flow.py
  custom_components/omnik_inverter/manifest.json
Labels: enhancement, no-stale

#101 Add Omnik3000TL and Bosswerk MI600 to the supported models
  README.md
Labels: documentation
