Repository robbinjanssen/home-assistant-omnik-inverter, pull requests merged in 2023-02, with the labels that each got.

#149 Add alarm code sensor to inverter
  custom_components/omnik_inverter/sensor.py
Labels: new-feature

#154 Reuse unique names from previous version
  custom_components/omnik_inverter/manifest.json
  custom_components/omnik_inverter/models.py
  custom_components/omnik_inverter/sensor.py
Labels: bugfix

#155 Do not pass session from home assistant, fails for some inverters
  custom_components/omnik_inverter/coordinator.py
Labels: bugfix

#156 config_flow: Print exception info to log
  custom_components/omnik_inverter/config_flow.py
  custom_components/omnik_inverter/coordinator.py
Labels: enhancement

#162 Sort JSON keys in manifest
  custom_components/omnik_inverter/manifest.json
Labels: ci
